name: hello_aqueduct
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  mongo_dart: ^0.4.4
  crypto: ^2.1.5
  jaguar_jwt: ^2.1.6

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0