name: hello_aqueduct
description: A blog using Aqueduct with MongoDB.
version: 0.0.1
author: Abdelouahed Medjoudja <abdeluached@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  mongo_dart: ^0.4.4
  crypto: ^2.1.5
  jaguar_jwt: ^2.1.6
  mime: any
  http_server: ^0.9.8+3

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0